apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fam-backend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - your-api.example.com
      secretName: fam-backend-tls
  rules:
    - host: your-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fam-backend
                port:
                  number: 80